# render.yaml
services:
  - type: web
    name: books-author-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: flask db upgrade && gunicorn --bind 0.0.0.0:$PORT --workers 3 "app:create_app()"
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0
      - key: SQLALCHEMY_DATABASE_URI
        fromDatabase:
          name: hello_books_api_database
          property: connectionString
    healthCheckPath: /books